name: Build Asasec Il2cppDumper

on:
  workflow_dispatch:

  push:
    branches:
      - main

jobs:

  build:

    runs-on: macos-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Show Xcode Version
        run: |
          xcodebuild -version

      - name: Clean Build
        run: |
          xcodebuild \
            -project "AsasecIl2cppDumper-Gui-App.xcodeproj" \
            -scheme "AsasecIl2cppDumper-Gui-App" \
            -configuration Release \
            -sdk iphoneos \
            -derivedDataPath "$PWD/build" \
            clean

      - name: Build iOS App
        run: |
          xcodebuild \
            -project "AsasecIl2cppDumper-Gui-App.xcodeproj" \
            -scheme "AsasecIl2cppDumper-Gui-App" \
            -configuration Release \
            -sdk iphoneos \
            -derivedDataPath "$PWD/build" \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            DEVELOPMENT_TEAM=""

      - name: Find APP
        run: |
          APP_PATH=$(find "$PWD/build" \
            -type d \
            -name "AsasecIl2cppDumper-Gui-App.app" \
            | head -n 1)

          if [ -z "$APP_PATH" ]; then
            echo "HATA: .app bulunamadı!"
            exit 1
          fi

          echo "APP:"
          echo "$APP_PATH"

          echo "APP içeriği:"
          find "$APP_PATH" -maxdepth 2 -print

      - name: Create IPA
        run: |
          APP_PATH=$(find "$PWD/build" \
            -type d \
            -name "AsasecIl2cppDumper-Gui-App.app" \
            | head -n 1)

          if [ -z "$APP_PATH" ]; then
            echo "HATA: .app bulunamadı!"
            exit 1
          fi

          rm -rf "$PWD/ipa"
          mkdir -p "$PWD/ipa/Payload"

          cp -R "$APP_PATH" \
            "$PWD/ipa/Payload/AsasecIl2cppDumper.app"

          cd "$PWD/ipa"

          zip -r \
            "$PWD/AsasecIl2cppDumper.ipa" \
            Payload

      - name: Check IPA
        run: |
          echo "IPA içeriği:"

          unzip -l \
            "$PWD/AsasecIl2cppDumper.ipa"

      - name: Upload IPA
        uses: actions/upload-artifact@v4

        with:
          name: AsasecIl2cppDumper-IPA
          path: AsasecIl2cppDumper.ipa
          if-no-files-found: error
